# Some Advanced numpy techniques
## Pseudorandom number generation

In [1]:
import numpy as np

In [2]:
samples = np.random.standard_normal(size=(4,4))
samples

array([[-0.44942317, -0.30073421,  0.94477876,  0.42442858],
       [-0.43321959,  0.30319344,  1.116541  ,  1.16105796],
       [ 0.27128195, -0.3432627 ,  0.66363088, -0.60029125],
       [ 1.3613617 ,  0.85967014,  0.41125006,  0.14794126]])

In [3]:
from random import normalvariate

In [4]:
N = 1_000_000

In [5]:
%timeit samples = [normalvariate(0,1) for _ in range(N)]

1.02 s ± 120 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [6]:
normalvariate(0,1)

0.6433652805330439

In [9]:
%timeit np.random.standard_normal(N)

37.7 ms ± 4.33 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [ ]:
np.random.standard_normal(1)

array([1.406255])

In [11]:
np.random.standard_normal(2)

array([-0.71628291,  0.67315982])

In [12]:
np.random.standard_normal(5)

array([-0.40172635,  0.66171275, -0.76585082,  2.00622361,  0.22123868])

In [15]:
rng = np.random.default_rng(seed=12345)
type(rng)

numpy.random._generator.Generator

In [14]:
data = rng.standard_normal((2, 3))
data

array([[-1.42382504,  1.26372846, -0.87066174],
       [-0.25917323, -0.07534331, -0.74088465]])

## Universal Functions: Fast Element wise Array functions

In [16]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [18]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [19]:
x = rng.standard_normal(8)
x

array([-1.42382504,  1.26372846, -0.87066174, -0.25917323, -0.07534331,
       -0.74088465, -1.3677927 ,  0.6488928 ])

In [20]:
y = rng.standard_normal(8)
y

array([ 0.36105811, -1.95286306,  2.34740965,  0.96849691, -0.75938718,
        0.90219827, -0.46695317, -0.06068952])

In [21]:
np.maximum(x, y)

array([ 0.36105811,  1.26372846,  2.34740965,  0.96849691, -0.07534331,
        0.90219827, -0.46695317,  0.6488928 ])

In [22]:
arr = rng.standard_normal(7) * 5
arr

array([ 3.94422172, -6.28334067,  2.87928757,  6.99489497,  6.6114903 ,
       -1.49849258,  4.51459671])

In [23]:
remainder, whole_part = np.modf(arr)

In [24]:
remainder

array([ 0.94422172, -0.28334067,  0.87928757,  0.99489497,  0.6114903 ,
       -0.49849258,  0.51459671])

In [25]:
whole_part

array([ 3., -6.,  2.,  6.,  6., -1.,  4.])

In [27]:
out = np.zeros_like(arr)
out

array([0., 0., 0., 0., 0., 0., 0.])

In [28]:
np.add(arr, 1)

array([ 4.94422172, -5.28334067,  3.87928757,  7.99489497,  7.6114903 ,
       -0.49849258,  5.51459671])

In [31]:
np.add(arr, 1, out=out)

array([ 4.94422172, -5.28334067,  3.87928757,  7.99489497,  7.6114903 ,
       -0.49849258,  5.51459671])

In [32]:
out

array([ 4.94422172, -5.28334067,  3.87928757,  7.99489497,  7.6114903 ,
       -0.49849258,  5.51459671])