In [2]:
import numpy as np

In [6]:
my_arr = np.arange(1_000_000)
my_arr

array([     0,      1,      2, ..., 999997, 999998, 999999])

In [7]:
my_list = list(my_arr)
my_list

[np.int64(0),
 np.int64(1),
 np.int64(2),
 np.int64(3),
 np.int64(4),
 np.int64(5),
 np.int64(6),
 np.int64(7),
 np.int64(8),
 np.int64(9),
 np.int64(10),
 np.int64(11),
 np.int64(12),
 np.int64(13),
 np.int64(14),
 np.int64(15),
 np.int64(16),
 np.int64(17),
 np.int64(18),
 np.int64(19),
 np.int64(20),
 np.int64(21),
 np.int64(22),
 np.int64(23),
 np.int64(24),
 np.int64(25),
 np.int64(26),
 np.int64(27),
 np.int64(28),
 np.int64(29),
 np.int64(30),
 np.int64(31),
 np.int64(32),
 np.int64(33),
 np.int64(34),
 np.int64(35),
 np.int64(36),
 np.int64(37),
 np.int64(38),
 np.int64(39),
 np.int64(40),
 np.int64(41),
 np.int64(42),
 np.int64(43),
 np.int64(44),
 np.int64(45),
 np.int64(46),
 np.int64(47),
 np.int64(48),
 np.int64(49),
 np.int64(50),
 np.int64(51),
 np.int64(52),
 np.int64(53),
 np.int64(54),
 np.int64(55),
 np.int64(56),
 np.int64(57),
 np.int64(58),
 np.int64(59),
 np.int64(60),
 np.int64(61),
 np.int64(62),
 np.int64(63),
 np.int64(64),
 np.int64(65),
 np.int64(66),
 np.i

In [8]:
%timeit my_arr2 = my_arr * 2

2.65 ms ± 98.1 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [9]:
%timeit my_list2 = [x * 2 for x in my_list]

120 ms ± 12.9 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


# The NumPy ndarray: A Multidimensional Array Object

In [11]:
data = np.array([[1.5, -0.1, 3], [0,-3,6.5]])
data

array([[ 1.5, -0.1,  3. ],
       [ 0. , -3. ,  6.5]])

In [12]:
data * 10

array([[ 15.,  -1.,  30.],
       [  0., -30.,  65.]])

In [13]:
data + data

array([[ 3. , -0.2,  6. ],
       [ 0. , -6. , 13. ]])

In [14]:
data.shape

(2, 3)

In [15]:
data.dtype

dtype('float64')

In [18]:
data1=[6,7.5, 8,0,1]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [21]:
data2 = [[1,2,3,4],[5,6,7,8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

- `ndim`: number of dimension 
- `nshape`: gives the overall shape of the array

In [22]:
arr2.ndim

2

In [23]:
arr2.shape

(2, 4)

## Creating n-D arrays of zeros and ones 

In [24]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [25]:
np.ones(15)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [28]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [35]:
ndarr = np.zeros((2, 3, 4))
ndarr

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [36]:
ndarr[0]

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [37]:
ndarr[1]

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [38]:
ndarr[0].shape

(3, 4)

In [39]:
ndarr[0][0]

array([0., 0., 0., 0.])

In [41]:
ndarr[0,0]

array([0., 0., 0., 0.])

In [42]:
np.empty((2,3,3))

array([[[1.37962049e-306, 1.24610791e-306, 1.11260959e-306],
        [1.69109959e-306, 9.34603679e-307, 1.42419802e-306],
        [1.78019082e-306, 4.45061456e-308, 1.24612081e-306]],

       [[1.37962049e-306, 9.34597567e-307, 1.29061821e-306],
        [1.78019625e-306, 1.11255866e-306, 8.90098127e-307],
        [9.34609790e-307, 3.91792279e-317, 6.97843598e+252]]])

> NOTE: The important thing here is that the np.empty may return non-zero values. This function returns uninitialized memort and thus may contain nonzero "grabage" values. We should only use this function only if we intend to populate the new array with data.

## Arithmatics with Numpy Arrays

In [48]:
arr_t = np.arange(6)
arr_t.reshape(2,3) # Reshape does not changes the underlying array.
arr_t

array([0, 1, 2, 3, 4, 5])

In [53]:
arr = arr_t.reshape(2, 3).astype('float')
arr

array([[0., 1., 2.],
       [3., 4., 5.]])

In [54]:
arr * arr

array([[ 0.,  1.,  4.],
       [ 9., 16., 25.]])

In [55]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [57]:
arr

array([[0., 1., 2.],
       [3., 4., 5.]])

In [58]:
1/arr

C:\Users\Najee\AppData\Local\Temp\ipykernel_13528\255282349.py:1: RuntimeWarning: divide by zero encountered in divide
  1/arr


array([[       inf, 1.        , 0.5       ],
       [0.33333333, 0.25      , 0.2       ]])

In [59]:
arr ** 2

array([[ 0.,  1.,  4.],
       [ 9., 16., 25.]])

In [61]:
arr2 = np.array([[0., 4., 1.], [7., 2.,12.]])
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [62]:
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])

## Basic Indexing and Slicing

In [63]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr[5] # 0 based index

np.int64(5)

In [ ]:
arr[9] # indexes are 0 based.

np.int64(9)

In [69]:
arr[10]

IndexError: index 10 is out of bounds for axis 0 with size 10

In [ ]:
arr[5:8] # inclusive start and exclusive end - [start_index, end_index)

array([5, 6, 7])

In [71]:
# brodcast 12 to n number of elements in the array
arr[5:8] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

> Important distinction between python built in list and array slices are views on the original array. Any change on the slice will get refected to the underlying array.

In [75]:
arr_slice = arr[5:8]
arr_slice

array([12, 12, 12])

In [76]:
arr_slice[1] = 12345
arr_slice

array([   12, 12345,    12])

In [77]:
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [78]:
arr_slice[:] = 64
arr_slice

array([64, 64, 64])

In [79]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [80]:
arr_slice_copy = arr[5:8].copy()
arr_slice_copy

array([64, 64, 64])

In [81]:
arr_slice_copy[1] = 123
arr_slice_copy

array([ 64, 123,  64])

In [82]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [83]:
arr2d = np.array([[1,2,3], [4,5,6], [7,8,9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [84]:
arr2d[:2] # start with select rows [0, 2)

array([[1, 2, 3],
       [4, 5, 6]])

In [85]:
arr2d[:2, 1:] # select rows [0, 2) and cols [1, end)

array([[2, 3],
       [5, 6]])

In [ ]:
lower_dim_slice = arr2d[1, 1:]
lower_dim_slice # only the 2nd rows two col values

array([5, 6])

In [90]:
lower_dim_slice.shape

(2,)

In [91]:
lower_dim_slice.ndim

1

In [92]:
# third column and only the first two rows
arr2d[:2, 2]

array([3, 6])

In [93]:
# all rows but just one col
arr2d[:, :1]

array([[1],
       [4],
       [7]])

In [94]:
arr2d[:2, 1:] = 0
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

### Boolean Indexing

In [96]:
names = np.array(["Bob", "Joe", "Will", "Bob", "Will", "Joe", "Joe"])
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [97]:
data = np.array([[4,7],[0,2],[-5,6], [0,0], [1,2], [-12,-4], [3,4]])
data

array([[  4,   7],
       [  0,   2],
       [ -5,   6],
       [  0,   0],
       [  1,   2],
       [-12,  -4],
       [  3,   4]])

In [98]:
names == "Bob"

array([ True, False, False,  True, False, False, False])

In [99]:
data[names=="Bob"]

array([[4, 7],
       [0, 0]])

- Notice the indexes selected from `data` 2D array based on the condition. Every True resulted in an index to be selected and the indecies equal to index of False were ignored.
- Remember data[0] is a 1D array and data[1] is another and so on, i.e. data[i] is a 1D array.
- The above slicing is selecting the rows. For Cols read along.

In [100]:
data[names=="Bob", 1:]

array([[7],
       [0]])

In [ ]:
data[names=="Bob", 1] # Just pull in the cols[1], rows values

array([7, 0])

In [102]:
names != "Bob"

array([False,  True,  True, False,  True,  True,  True])

In [103]:
~(names=="Bob")

array([False,  True,  True, False,  True,  True,  True])

In [104]:
data[~(names=="Bob")]

array([[  0,   2],
       [ -5,   6],
       [  1,   2],
       [-12,  -4],
       [  3,   4]])

In [105]:
cond = names == "Bob"
cond

array([ True, False, False,  True, False, False, False])

In [106]:
data[~cond]

array([[  0,   2],
       [ -5,   6],
       [  1,   2],
       [-12,  -4],
       [  3,   4]])

In [107]:
mask = (names=="Bob") | (names=="Will")
mask

array([ True, False,  True,  True,  True, False, False])

In [108]:
data[mask]

array([[ 4,  7],
       [-5,  6],
       [ 0,  0],
       [ 1,  2]])

In [ ]:
data_add_temp = data + 100
data_add_temp # data + 100 adds 100 to every element in the array.

array([[104, 107],
       [100, 102],
       [ 95, 106],
       [100, 100],
       [101, 102],
       [ 88,  96],
       [103, 104]])

In [112]:
data

array([[  4,   7],
       [  0,   2],
       [ -5,   6],
       [  0,   0],
       [  1,   2],
       [-12,  -4],
       [  3,   4]])

In [113]:
data < 0

array([[False, False],
       [False, False],
       [ True, False],
       [False, False],
       [False, False],
       [ True,  True],
       [False, False]])

In [114]:
data[data < 0] = 0
data

array([[4, 7],
       [0, 2],
       [0, 6],
       [0, 0],
       [1, 2],
       [0, 0],
       [3, 4]])

In [115]:
data[names!="Joe"] = 7
data

array([[7, 7],
       [0, 2],
       [7, 7],
       [7, 7],
       [7, 7],
       [0, 0],
       [3, 4]])

### Fancy Indexing

## Transposing Arrays and Swapping Axes

In [119]:
arr = np.arange(15).reshape((3,5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [120]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [121]:
np.dot(arr.T, arr)

array([[125, 140, 155, 170, 185],
       [140, 158, 176, 194, 212],
       [155, 176, 197, 218, 239],
       [170, 194, 218, 242, 266],
       [185, 212, 239, 266, 293]])